# This is an **example** API to demontstrate features of OpenAPI specification.
# It doesn't cover all OpenAPI features. For more full example check out: https://github.com/APIs-guru/petstore_extended

swagger: '2.0'
# You should specify common part of your endpoints in the following format:
#   <schemes>://<host><basepath>
schemes:
  - http # Remove if your API doesn't support HTTP
  - https # Remove if your API donsn't support HTTPS
host: example.com # Replace with your hostname. You can also specify port e.g. example.com:777
basePath: /api/v1 # Replace with your basePath. Note: SHOULD begin with '/'.
info:
  # Describe your API here, you can use GFM (https://guides.github.com/features/mastering-markdown) here
  description: |
    This is an **example** API to demontstrate features of OpenAPI specification
    # Introduction
    This specification is intended to to be a good starting point for describint your API in
    [OpenAPI/Swagger format](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md).
    It also demonstrates features of [generator-openapi-repo](https://github.com/Rebilly/generator-openapi-repo) tool and
    [ReDoc](https://github.com/Rebilly/ReDoc) documentation engine. So beyond the standard OpenAPI syntax we use a few
    [vendor extensions](https://github.com/Rebilly/ReDoc/blob/master/docs/redoc-vendor-extensions.md).

    # OpenAPI Specification
    The goal of The OpenAPI Specification is to define a standard, language-agnostic interface to REST APIs which
    allows both humans and computers to discover and understand the capabilities of the service without access to source
    code, documentation, or through network traffic inspection. When properly defined via OpenAPI, a consumer can
    understand and interact with the remote service with a minimal amount of implementation logic. Similar to what
    interfaces have done for lower-level programming, OpenAPI removes the guesswork in calling the service.

  version: '1.0.0' # Your API version
  # It can be any string but it is better to use semantic versioning: http://semver.org/
  # Warning: OpenAPI require version to be string, but without quotation YAML can recognize it as number.

  title: Example.com # Replace with your API title
  # Keep it simple. Don't add "API" or verison at the end of the string.

  termsOfService: 'https://example.com/terms/' # [Optional] Replace with an URL to your ToS
  contact:
    email: contact@example.com # [Optional] Replace with your contact email
    url: 'http://example.com/contact' # [Optional] Replace with link to your contact form
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://apis.guru/openapi-template/logo.png'
externalDocs:
  description: Find out how to create Github repo for your OpenAPI spec.
  url: 'https://github.com/Rebilly/generator-openapi-repo'
produces:
  - application/vnd.api+json
consumes:
  - application/json
tags:
  - name: Check Ins
    description: Checkin Operations
securityDefinitions:
  main_auth: # security definition name (you can name it as you want)
    type: oauth2 # authorization type, one of: oauth2, basic, apiKey
    # the following options are specific to oauth2 type
    authorizationUrl: 'http://example.com/api/oauth/dialog'
    flow: implicit
    scopes:
      'read:users': read users info
      'write:users': modify or remove users
  OAuth2: # security definition name (you can name it as you want)
    type: oauth2 # authorization type, one of: oauth2, basic, apiKey
    # the following options are specific to oauth2 type
    authorizationUrl: 'http://example.com/api/oauth/dialog'
    flow: implicit
    scopes:
      read_checkins: read checkin for a membership

  api_key: # security definition name (you can name it as you want)
    type: apiKey
    # The following options are specific to apiKey type
    in: header # Where API key will be passed: header or query
    name: api_key # API key paramteer name
  basic_auth: # security definition name (you can name it as you want)
    type: basic

# Holds the relative paths to the individual endpoints. The path is appended to the
# basePath in order to construct the full URL.
paths:

  '/check_ins':
    post:
      tags:
        - Check Ins
      summary: Check In with credentials
      description: |
        checkin with a check in token or login / password
      parameters:

    get:
      tags:
        - Check Ins


  '/memberships/{membershipId}/check_ins/current':
    parameters:
      - name: mebershipId
        in: path
        description: 'The id of the membership the checkins belong to.'
        required: true
        type: string
      - name: stop
        in: query
        type: string
        format: date-time
        description: 'Optional end time - possible to check a member out in the past'
    delete:
      tags:
        - Check Ins
      summary: Check out a member
      operationId: checkOut
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/checkins'
          examples:
            application/vnd.api+json:
              data:
                id: a8c12f62ac8df98d29de357180d673e1
                type: checkins
                attributes:
                  start: 2018-12-06T10:00:00Z
                  stop: 2018-12-06T11:00:00Z
                relationships:
                  memberhip:
                    data:
                      id: c9a99a71ac8df98d29de357180d273d3
                      type: memberships
                  space:
                    data:
                      id: c9a99a71ac8df98d29de357180d273d3
                      type: spaces
                  time_pass:
                    data:
                      id: c9a99a71ac8df98d29de357180d273d3
                      type: time_passes

        403:
          description: Forbidden
        404:
          descripton: Member not found



  '/memberships/{membershipId}/check_ins':

    parameters:
      - name: mebershipId
        in: path
        description: 'The id of the membership the checkins belong to.'
        required: true
        type: string

    # parameters list that are used with each operation for this path
    post:
      tags:
        - Check Ins
      summary: Check In a member
      descripition: |
        Check a member in into a given space
      operationId: checkIn
      parameters:
        - name: body
          in: body
          schema:
            $ref: '#/definitions/checkin_requests'
          examples:
              data:
                attributes:
                  token: 'optional RFID TOKEN'
                  login: 'optional login'
                  password: 'optional password'
                  start: 2018-12-07T12:09:51Z






    get:
      tags:
        - Check Ins

      # summary is up to 120 symbold but we recommend to be shortest as possible
      summary: Get member check-ins

      description: |
        Get user check-ins in the given time range, across the network (if space is part of one)
      # you can use GFM in operation description too: https://guides.github.com/features/mastering-markdown

      # operationId should be unique across the whole specification
      operationId: getUserCheckIn


      # list of parameters for the operation
      parameters:
        - name: from
          in: query # place where paramter is passed: path, header, query or body, formData
          description: From date
          # type of the paramter: string, number, integer, boolean, array
          type: string
          format: date-time
        - name: to
          in: query # place where paramter is passed: path, header, query or body, formData
          description: To date
          # type of the paramter: string, number, integer, boolean, array
          type: string
          format: date-time

      # security schemas applied to this operation
      security:
        - OAuth2:
          - read_checkins
      # overwriting default global produces
      produces:
        - application/vnd.api+json
      responses: # list of responses
        200:
          description: Success
          schema: # response schema can be specified for each response
            $ref: '#/definitions/checkins'
          examples:
          # repsonse samples for each type operation produces
            application/vnd.api+json:
              data:
                - id: a8c12f62ac8df98d29de357180d673e1
                  type: checkins
                  attributes:
                    start: 2018-12-06T10:00:00Z
                    stop: 2018-12-06T11:00:00Z
                  relationships:
                    memberhip:
                      data:
                        id: c9a99a71ac8df98d29de357180d273d3
                        type: memberships
                    space:
                      data:
                        id: c9a99a71ac8df98d29de357180d273d3
                        type: spaces
                    time_pass:
                      data:
                        id: c9a99a71ac8df98d29de357180d273d3
                        type: time_passes
        403:
          description: Forbidden
        404:
          description: Membership not found
    # documentation for PUT operation for this path
    put:
      tags:
        - User
      summary: Updated user
      description: This can only be done by the logged in user.
      operationId: updateUser
      produces:
        - application/json
      parameters:
        - name: username
          in: path
          description: The name that needs to be updated
          required: true
          type: string
        - in: body
          name: body
          description: Updated user object
          required: true
          # for body parameter you should specify request schema instead of type
          schema:
            $ref: '#/definitions/User'
      security:
        - main_auth:
          - 'write:users'
      responses:
        '200':
          description: OK
        '400':
          description: Invalid user supplied
        '404':
          description: User not found

  '/echo':
    post:
      tags:
        - Echo
      summary: Echo test
      description: Receive the exact message you've sent
      operationId: echo
      parameters:
        - name: message
          in: body
          description: 'Echo payload'
          required: true
          schema:
            type: string
            example: 'Hello world!'
      security:
        - api_key: []
      responses:
        '200':
          description: 'OK'
          examples:
            'application/json': 'Hello world!'
          schema:
            type: string
          # docuemnt headers for this repsonse
          headers:
            X-Rate-Limit: # Header name
              type: integer # Header value type
              format: int32 # Header value format
              description: calls per hour allowed by the user
            X-Expires-After:
              type: string
              format: date-time
              description: date in UTC when token expires
# An object to hold data types that can be consumed and produced by operations.
# These data types can be primitives, arrays or models.
definitions:
  checkin_requests:
    type: object
    additionalProperties: false
    required:
      - type
      - attributes
      - relationships
    properties:
      type:
        type: 'string'
        pattern: "checkin_request"
      attributes:
        type: object
        additionalProperties: false
        properties:
          token:
            type: string
            example: Optional RFID token
            description: used if membershipId is not present (optional)
          start:
            type: string
            format: date-time
            required: false
            description: the checkin start time - possible to check a user in in the past (optional)
      relationships:
        type: object
        additionalProperties: false
        properties:
          space:
            type: object
            description: the space to check the user in to
            properties:
              data:
                type: object
                example:
                  type: spaces
                  id: 123


  checkins:
    type: object
    required:
      - type
      - attributes
    additionalProperties: false
    properties:
      type:
        type: string
        pattern: "checkins"
      attributes:
        type: object
        additionalProperties: false
        properties:
          start:
            type: string
            format: date-time
          stop:
            type: string
            format: date-time


  Email:
    description: User email address
    type: string
    format: email
    example: john.smith@example.com
  User:
    type: object
    properties:
      username:
        description: User supplied username
        type: string
        minLength: 4
        example: John78
      firstName:
        description: User first name
        type: string
        minLength: 1
        example: John
      lastName:
        description: User last name
        type: string
        minLength: 1
        example: Smith
      email:
        $ref: '#/definitions/Email'
